spring:
  datasource:
    url: jdbc:mysql://localhost:3306/axon_study?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: guest
      password: guest